### ISSUE TITLE
README.md中的项目structure是自动生成的吗？

### ISSUE THREAD

**Issue by hui61** [iofu728/spider#29]
使用什么工具生成的structure？

**Comment by iofu728** [comment]
@hui61 
> 使用什么工具生成的structure？

hi, the file structure was generated by the [The Tree Command for Linux Homepage](http://mama.indstate.edu/users/ice/tree/)

On the homepage, u will get the usage.

And this is my shell script.
```bash
tree -I '__pycache__|venv|data|*.ipynb|*test*|*.md'
```
